In [1]:
import numpy as np
import tools

In [2]:
B2 = np.array([[-1, 0, 0], [0, 0, 1], [0, 1, 0]])

In [3]:
B3 = np.linalg.inv(B2)

In [4]:
print(B3)

[[-1. -0. -0.]
 [ 0.  0.  1.]
 [ 0.  1.  0.]]


In [5]:
A2 = np.array([[1, 0, 0, 0], [0, 0, 1, 0], [0, -1, 0, 0], [0, 0, 0, 1]])
A1 = np.array([[-0.5, 0, 0, 21], 
               [0, -0.25, 0, 9.5], 
               [0, 0, 0.5, -24.75], 
               [0, 0, 0, 1]])

In [6]:
A2 @ A1

array([[ -0.5 ,   0.  ,   0.  ,  21.  ],
       [  0.  ,   0.  ,   0.5 , -24.75],
       [  0.  ,   0.25,   0.  ,  -9.5 ],
       [  0.  ,   0.  ,   0.  ,   1.  ]])

In [7]:
aff1 = A1

In [8]:
tA1 = tools.compute_affine_to_fpmat(aff1)
taff2 = tools.compute_affine_from_fp((True, False, False), (0, 2, 1))
tA2 = tools.compute_affine_to_fpmat(taff2)
tQ = tools.compute_change_of_base_matrix(tA1, tA2)
tP = tools.ext.np.linalg.inv(tQ) # same as compute_change_of_base(A2, A1) indeed. 
taff3 = tools.compute_matrix_to_affine(tP)
taff4 = taff3 @ aff1

In [9]:
tP

array([[ 1.,  0.,  0.],
       [ 0.,  0.,  1.],
       [-0., -1., -0.]])

In [10]:
aff1 = np.array([
    [0, -0.5, 0, 21], 
    [-0.25, 0, 0, 9.5], 
    [0, 0, 0.5, -24.75], 
    [0, 0, 0, 1]])
A2 = tools.compute_affine_to_fpmat(aff1)
print(A2)

[[ 0. -1.  0.]
 [-1.  0.  0.]
 [ 0.  0.  1.]]


In [11]:
tools.ext.reload(tools)

<module 'tools' from '/home/becqg/data/2024Phantom3D/derivatives/1-validate-orientations/code/tools.py'>

In [12]:
>>> A1 = np.arange(9).reshape((3, 3))
>>> tools.compute_matrix_to_affine(A1)

array([[0., 1., 2., 0.],
       [3., 4., 5., 0.],
       [6., 7., 8., 0.],
       [0., 0., 0., 1.]])

In [13]:
>>> tools.compute_affine_from_fp((True, False, True), (2, 1, 0))

array([[ 0.,  0., -1.,  0.],
       [ 0.,  1.,  0.,  0.],
       [-1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [14]:
>>> aff1 = np.eye(4) 
>>> aff1[:3, :3] *= 0.25
>>> tools.compute_transformed_affine(aff1, (True, False, True), (2, 1, 0)) 

array([[ 0.  ,  0.  , -0.25,  0.  ],
       [ 0.  ,  0.25,  0.  ,  0.  ],
       [-0.25,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  1.  ]])

In [15]:
>>> A0 = np.arange(24).reshape(3, 2, 4)
>>> patterns = tools.compute_patterns(A0)
>>> patterns["False_False_False_(0, 1, 2)"]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [16]:
patterns["True_False_True_(2, 1, 0)"]

array([[[19, 11,  3],
        [23, 15,  7]],

       [[18, 10,  2],
        [22, 14,  6]],

       [[17,  9,  1],
        [21, 13,  5]],

       [[16,  8,  0],
        [20, 12,  4]]])